# Generated by Django 4.2.29 on 2026-03-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
